### ISSUE TITLE
Integration of Beet

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/gwallet#2]
This is a non-js non-web app and would be beautiful to get a library working for C++ beet support (similar to beet-js).

Is that something that could be of interest?

**Comment by oxarbitrage** [comment]
Please elaborate more on the question, I cant understand it. Thanks.

**Comment by sschiessl-bcp** [comment]
The question was at a time where I did not understand completely what it is intended to be. cli wallet has its own key management and for the use case of being a wrapper beet is not necessary.

**Comment by oxarbitrage** [comment]
Got it, thank you. Feel free to open other issues as needed.
