### ISSUE TITLE
About Install

### ISSUE THREAD

**Issue by shulthz** [bitshares/gwallet#22]
> Install
> 
> Ubuntu instructions assuming you already have all needed to install bitshares-core software.
> 
> Add wxWidgets to your system:
> 
> `sudo apt-get install libwxgtk3.0-dev`

should：

`sudo apt-get update`

first..

**Comment by oxarbitrage** [comment]
Added at https://github.com/bitshares/gwallet/commit/2ad1ddc2917c3cdcff865b3fa105b23770064849, thanks.
