### ISSUE TITLE
The translations: problem of zh/gwallet.po

### ISSUE THREAD

**Issue by shulthz** [bitshares/gwallet#24]
I didn't update the file of gwallet/i18n/zh/gwallet.mo, it seems there have someting is wrong in changing the language.

**Comment by oxarbitrage** [comment]
Thanks, i forgot the .mo is needed. For reference the .mo can be compiled with [Poedit](https://poedit.net/) .

I pushed the .mo at https://github.com/bitshares/gwallet/commit/2b9421bd7ac72dd503b52556d19a3f1477cd0dcd so now the translations made at https://github.com/bitshares/gwallet/pull/23 should be visible.
